const generateConstants = baseType => ({
    [baseType]: baseType,
    [`${baseType}_REQUEST`]: `${baseType}_REQUEST`,
    [`${baseType}_SUCCESS`]: `${baseType}_SUCCESS`,
    [`${baseType}_FAILURE`]: `${baseType}_FAILURE`
})

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
}

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    AUTHENTICATE_REQUEST: 'USER_AUTHENTICATION_REQUEST',
    AUTHENTICATE_SUCCESS: 'USER_AUTHENTICATION_SUCCESS',
    AUTHENTICATE_FAILURE: 'USER_AUTHENTICATION_FAILURE',

    RESET_PASSWORD_REQUEST: 'USER_PASSWORD_RESET_REQUEST',
    RESET_PASSWORD_COMPLETE: 'PASSWORD_RESET_REQUEST_COMPLETE',

    NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED'
}

export const userProfileConstants = {
    USER_PROFILE: 'USER_PROFILE',
    USER_PROFILE_REQUEST: 'USERS_PROFILE_REQUEST',
    USER_PROFILE_SUCCESS: 'USERS_PROFILE_SUCCESS',
    USER_PROFILE_FAILURE: 'USERS_PROFILE_FAILURE',

    USER_FLAG: 'USER_FLAG',
    USER_FLAG_REQUEST: 'USERS_FLAG_REQUEST',
    USER_FLAG_SUCCESS: 'USERS_FLAG_SUCCESS',
    USER_FLAG_FAILURE: 'USERS_FLAG_FAILURE',

    USER_STATS: 'USER_STATS',
    USER_STATS_REQUEST: 'USERS_STATS_REQUEST',
    USER_STATS_SUCCESS: 'USERS_STATS_SUCCESS',
    USER_STATS_FAILURE: 'USERS_STATS_FAILURE'
}

export const stationConstants = {
    STATION_REQUEST: 'GET_STATION_REQUEST',
    STATION_DETAIL: 'STATION_INFORMATION',
    STATIONS_LIST: 'LIST_OF_STATIONS',
    STATIONS_LOCATIONS_REQUEST: 'GET_LOCATION_REQUEST',
    STATIONS_LOCATIONS_DETAIL: 'LOCATIONS_INFORMATION',
    STATIONS_TRENDING: 'TRENDING_STATIONS',
    ...generateConstants('USER_FAVORITE_A_STATION')
}

export const searchConstants = {
    ...generateConstants('SEARCH_FLAG'),
    ...generateConstants('SEARCH_USER'),
    ...generateConstants('SEARCH_STATION')
    // SEARCH_FLAG: 'SEARCH_FLAG',
    // SEARCH_FLAG: 'SEARCH_FLAG_REQUEST',
    // SEARCH_FLAG: 'SEARCH_FLAG_SUCCESS',
    // SEARCH_FLAG: 'SEARCH_FLAG_ERROR',

    // SEARCH_USER: 'SEARCH_USER',
    // SEARCH_USER: 'SEARCH_USER_REQUEST',
    // SEARCH_USER: 'SEARCH_USER_SUCCESS',
    // SEARCH_USER: 'SEARCH_USER_ERROR',

    // SEARCH_STATION: 'SEARCH_STATION',
    // SEARCH_STATION: 'SEARCH_STATION_REQUEST',
    // SEARCH_STATION: 'SEARCH_STATION_SUCCESS',
    // SEARCH_STATION: 'SEARCH_STATION_ERROR'
}

export const genreConstants = {
    GENRE_ALL: 'GENRE_ALL',
    GENRE_ALL_REQUEST: 'GENRE_ALL_REQUEST',
    GENRE_ALL_SUCCESS: 'GENRE_ALL_SUCCESS',
    GENRE_ALL_ERROR: 'GENRE_ALL_ERROR',

    GENRE_TREE: 'GENRE_TREE',
    GENRE_TREE_REQUEST: 'GENRE_TREE_REQUEST',
    GENRE_TREE_SUCCESS: 'GENRE_TREE_SUCCESS',
    GENRE_TREE_ERROR: 'GENRE_TREE_ERROR'
}

export const widgetConstants = {
    WIDGET_GROUP: 'WIDGET_GROUP',
    WIDGET_GROUP_REQUEST: 'WIDGET_GROUP_REQUEST',
    WIDGET_GROUP_SUCCESS: 'WIDGET_GROUP_SUCCESS',
    WIDGET_GROUP_ERROR: 'WIDGET_GROUP_ERROR',

    WIDGET_DETAIL: 'WIDGET_DETAIL',
    WIDGET_DETAIL_REQUEST: 'WIDGET_DETAIL_REQUEST',
    WIDGET_DETAIL_SUCCESS: 'WIDGET_DETAIL_SUCCESS',
    WIDGET_DETAIL_ERROR: 'WIDGET_DETAIL_ERROR'
}
